version: '3.8'

services:
  app-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    command: ./start.sh