---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockzrs-relay-service
  namespace: stockzrs-relay-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockzrs-relay-service
  template:
    metadata:
      labels:
        app: stockzrs-relay-service
    spec:
      containers:
      - name: stockzrs-relay-service
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stockzrs-relay-service
  namespace: stockzrs-relay-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: stockzrs-relay-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
